services:
  backend:
    image: ze2l/ppituruppaturu-backend:latest
    restart: unless-stopped
    container_name: pitturu-backend-green
    ports:
      - "127.0.0.1:8082:8080"
      - "127.0.0.1:8084:8082"
    environment:
      - DSN=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@pitturu-postgres:5432/${POSTGRES_DB:-pitturu_db}?sslmode=disable
      - REDIS_URL=redis://pitturu-redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    external_links:
      - pitturu-postgres:postgres
      - pitturu-redis:redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ze2l/ppituruppaturu-frontend:latest
    restart: unless-stopped
    container_name: pitturu-frontend-green
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://152.67.201.101/api
      - NEXT_PUBLIC_WS_URL=ws://152.67.201.101/ws
      - NODE_ENV=production
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s