name: ppituru-blue

networks:
  ppituru-core:
    external: true

services:
  backend:
    image: ${BACKEND_IMAGE:-ze2l/ppituruppaturu-backend:latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:8083:8082"
    networks:
      - ppituru-core
    environment:
      - DSN=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@ppituru-postgres:5432/${POSTGRES_DB:-ppituru_db}?sslmode=disable
      - REDIS_URL=redis://ppituru-redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI:-http://localhost:3000/auth/kakao/callback}
    healthcheck:
      test: ["CMD", "/server", "--healthcheck"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  frontend:
    image: ${FRONTEND_IMAGE:-ze2l/ppituruppaturu-frontend:latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - ppituru-core
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_WS_URL=/ws
      - NODE_ENV=production
      - NEXT_PUBLIC_KAKAO_CLIENT_ID=${NEXT_PUBLIC_KAKAO_CLIENT_ID}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://ppituruppaturu.com}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
