name: ppituru-green

networks:
  ppituru_default:
    external: true

services:
  backend:
    image: ${BACKEND_IMAGE:-ze2l/ppituruppaturu-backend:latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:8080"
      - "127.0.0.1:8084:8082"
    networks:
      - ppituru_default
    environment:
      - DSN=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@ppituru-postgres:5432/${POSTGRES_DB:-ppituru_db}?sslmode=disable
      - REDIS_URL=redis://ppituru-redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    healthcheck:
      test: ["CMD", "/server", "--healthcheck"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  frontend:
    image: ${FRONTEND_IMAGE:-ze2l/ppituruppaturu-frontend:latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - ppituru_default
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_WS_URL=/ws
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
