version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: pitturu-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pitturu_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: pitturu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    image: ze2l/ppituruppaturu-backend:latest
    restart: unless-stopped
    container_name: pitturu-backend-blue
    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:8083:8082"
    environment:
      - DSN=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-pitturu_db}?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ze2l/ppituruppaturu-frontend:latest
    restart: unless-stopped
    container_name: pitturu-frontend-blue
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://152.67.201.101/api
      - NEXT_PUBLIC_WS_URL=ws://152.67.201.101/ws
      - NODE_ENV=production
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data: