run:
  timeout: 5m

issues:
  exclude-files:
    - "^pp-backend/docs/.*"   # 생성물 폴더면 필요 시 제외
  exclude-dirs:
    - "vendor"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - gosimple
    - typecheck
    - unused
    - gocritic
    - dupl
    - gofmt
    - goimports
    - misspell
    - prealloc
  disable:
    - depguard

linters-settings:
  govet:
    enable:
      - shadow   # linters.govet.check-shadowing 대체

output:
  formats:
    - format: github-actions
