run:
  timeout: 5m

issues:
  exclude-files:
    - "^pp-backend/docs/.*"   # 생성물 폴더면 필요 시 제외
  exclude-dirs:
    - "vendor"

linters:
  enable:
    - gofmt
    - goimports
  disable:
    - typecheck  # 너무 엄격해서 CI에서 실패
    - depguard
    - dupl
    - gocritic
    - gosimple
    - staticcheck
    - revive
    - misspell
    - prealloc
    - govet
    - errcheck
    - ineffassign
    - unused

linters-settings:
  govet:
    enable-all: false

output:
  formats:
    - format: colored-line-number
