run:
  timeout: 5m

issues:
  exclude-files:
    - "^pp-backend/docs/.*"   # 생성물 폴더면 필요 시 제외
  exclude-dirs:
    - "vendor"

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - unused
  disable:
    - depguard
    - dupl
    - gocritic
    - gosimple
    - staticcheck
    - revive
    - goimports
    - misspell
    - prealloc

linters-settings:
  govet:
    enable-all: false

output:
  formats:
    - format: colored-line-number
